code: numpy-basics
title: NumPy Basics
toc:
  - code: numpy-array-basics
    title: NumPy Array Basics
    id: e12686df-3eab-417a-ad31-ff60cc5fc147
    topics:
      - code: numpy-array
        title: NumPy Array
        id: 0207bf54-d053-4407-ab21-66736ea00555
      - code: one-dimensional-array
        title: One Dimensional Array
        id: cf4a089b-e86a-454b-8a2a-4d69748fa86c
      - code: n-dimensional-array
        title: N Dimensional Array
        id: 2e3e2f0b-b731-4113-bc6c-31c45f01f21f
      - code: array-creation
        title: Array Creation
        id: bd142498-c958-4fa7-86f4-0783c5beb656
      - code: data-types
        title: Data Types
        id: 563b0fb5-d897-406d-9621-88b7ed817812
      - code: data-type-conversion
        title: Data Type Conversion
        id: a8a8e2c1-e9e1-481e-bc3b-e7c6bb895ba0
  - code: indexing-slicing-iterating
    title: 'Indexing, Slicing, Iterating'
    id: b8514d84-35c5-4857-bca3-f71ca98bc7a5
    topics:
      - code: introduction
        title: Introduction
        id: 6c22f6d0-4971-4f3b-a649-9fe69567005a
      - code: indexing-and-slicing-one-dimensional-array
        title: Indexing and Slicing One Dimensional Array
        id: 54821ad1-927e-4d23-a6db-a1fd09c253e0
      - code: indexing-multi-dimensional-arrays
        title: Indexing Multi Dimensional Arrays
        id: 55165783-a608-41fb-8fcd-d35c43e6cad1
  - code: about
    title: About
    id: 5e1a0bb5-ec8f-4284-b9cd-2d2a1cb8f1c5
    topics:
      - code: book
        title: Book
        id: 1562a9db-2625-49d3-82ad-5ad912925cf6
      - code: author
        title: Author
        id: 01bae7f3-9589-4609-9134-79b9e5b898b0
