code: numpy-basics
title: NumPy Basics
toc:
  - code: numpy-array-basics
    title: NumPy Array Basics
    id: e12686df-3eab-417a-ad31-ff60cc5fc147
    topics:
      - code: numpy-array
        title: NumPy Array
        id: 0207bf54-d053-4407-ab21-66736ea00555
      - code: one-dimensional-array
        title: One Dimensional Array
        id: cf4a089b-e86a-454b-8a2a-4d69748fa86c
      - code: n-dimensional-array
        title: N Dimensional Array
        id: 2e3e2f0b-b731-4113-bc6c-31c45f01f21f
  - code: about
    title: About
    id: 5e1a0bb5-ec8f-4284-b9cd-2d2a1cb8f1c5
    topics:
      - code: book
        title: Book
        id: 1562a9db-2625-49d3-82ad-5ad912925cf6
      - code: author
        title: Author
        id: 01bae7f3-9589-4609-9134-79b9e5b898b0
